#Сonfiguration file for Unpacker.py
#!!!Directory names must be in English and not contain spaces!!!
#In one line, specify the absolute path to the directory for example:
#/home/
#OR
#/mnt/
#A drive must be mounted in /mnt/
#Write the path to the directory where you want to unpack the archives on the line below. For example:
#/home/username/directory/
#Write the path to the directory where you want to unpack the archives on the line above
#!!!DO NOT CORRECT ANYTHING ELSE IN THIS CONFIG, EVERYTHING MAY BROKE!!!
