#Сonfiguration file for Archiver.py
#!!!Directory names must be in English and not contain spaces!!!
#In one line, specify the absolute path to the directory separated by spaces, for example:
#/home/ /etc/pacman.d/
#Write your directories in the line below
#/home/username/.config/
#Write your directories on the line above
#In one line, specify the absolute path to the directory for example:
#/home/
#OR
#/mnt/
#A drive must be mounted in /mnt/
#Write the path to the directory in which the file will be saved in the line below
#/home/username/directory/
#Write the path to the directory in which the file will be saved on the line above
#!!!DO NOT CORRECT ANYTHING ELSE IN THIS CONFIG, EVERYTHING MAY BROKE!!!
#!!!PLEASE DO NOT COPY THE WHOLE ROOT!!!
